### PR TITLE
Create my_transcriptome_samples.tsv

### PR DESCRIPTION
**Pull request by ACharbonneau**
This is the file where your sample names go. For *this* one it needs to be edited to have the paths to *just* the few samples you want to use to build the transcriptome.

This is a tsv file, so the columns are tab separated, and eelpond is *super* picky about it. The *only* spaces in the entire file should be the tabs separating the columns. If you have spaces in the file names or any of the metadata, replace them with underscores or dashes. All of your input files *must* be gzipped!

fq1 needs to be the path to the forward read for a sample and fq2 is the reverse reads. i'm pretty sure that sample can be whatever name you want for each. I'm not 100% sure what unit is, condition is some descriptor of your experiment...whatever your treatment was. For this particular file, I think only fq1 and fq2 matter because we're just building a transcriptome, not running an analysis, but I've asked for clarification here: https://github.com/dib-lab/eelpond/issues/81

### CODE REVIEW

**Comment by ACharbonneau** [comment]
OK, I'm not sure this is all going to work on the first try...in fact, it almost certainly won't, but I think I have the input files at least close to right. Lets see what errors you get :)
For step 2, we need to talk about what your model is/what to put into the DESeq2 options, but I think the rest is mostly right.

**Comment by mandyfrazier** [comment]
Thanks Amanda!! I think that all makes sense.... I realize now, though, that I only saved the sequence files from _after_ running Trinity, because I had decided that pre-Trinity files were intermediate that I wouldn't use again. So all of my sequences files are "filename_R1.cor.fq.gz.P.qtrim.gz" or "filename_R2.cor.fq.gz.P.qtrim.gz". I thought that the "P" indicated that they are paired, so I'm not sure whey there's a R1 and R2 for every file 🤔. Can I use those for Trinity? Of course I still have the raw initial data, so if I can't use the post-Trinity sequence files to put back into Trinity, then I can start from the veryyyy beginning again. I have the codes I used to smoosh the files and run FastQC so hopefully that wouldn't be too arduous....

**Comment by ACharbonneau** [comment]
The files are paired end, but generally the pairs are kept separate, so that seems fine. I'm not 100% sure why Trinity would give you sequence files like that though...to you mean post-trimmomatic?

**Comment by mandyfrazier** [comment]
Yes I mean post- trimmomatic, I was thinking of it as post- Trinity because I ran Trimmomatic within Trinity.

**Comment by mandyfrazier** [comment]
I'm thinking of using six samples for reference transcriptome: 

1. cannibal of the river-adapted family (RV)
2. cannibal of lake-adapted family 1 (Ma)
3. cannibal of lake-adapted family 2 (Mb)
4. non-cannibal of the river-adapted family (RV)
5. non-cannibal of lake-adapted family 3 (Mc) 
6. non-cannibal of lake-adapted family 4 (Md)

 
This way every family is represented once (except for RV, they get two), and there are river-adapted and lake-adapted families represented for both feeding strategies. Does that seem reasonable?

**Comment by mandyfrazier** [comment]
When I ran Trinity before, I used the default Trimmomatic parameters (sliding window 4:5, leading:5, trailing:5, minlen:25). Will trimmomatic trim the sequence files again or is it smart enough to know that it's already been done? Could we just run Trinity without Trimmomatic in eelpond? 
Sorry for the deluge of questions 😬

**Comment by ACharbonneau** [comment]
I think those trimmed files should be okay to use. They just won't get trimmed much/at all in the trimming step. 

And for the samples themselves, do you think that the different families will have different genes expressed? The build will probably be easier to assemble and have fewer mis-assembled transcripts if we minimize the variation. If the families have SNPs, deletions, other mutations between them, then mixing their reads will make it more likely that genes get assembled incorrectly, especially for genes that have very similar orthologs. But, if you think that some genes just only exist in one family or another, then we might want to diversify the families to catch them all. If they're all the same species that seems unlikely though. I think I would pick either the cannibals or non-cannibals from one family. That way you'll minimize the amount of mutations between samples. And if you want to go back and look at sequence changes in your genes later, you'll have a clearer idea of whether any given allele in your reference was the cannibal or non-cannibal version.

**Comment by ACharbonneau** [comment]
those parameters in trimmomatic only trims bases if they're low quality, so it shouldn't trim them a great deal more, but what we can do is get rid of some of the trimming parameters so that it effectively doesn't do anything. I'll edit the file in a sec.

**Pull request merged**
